// ─── App Theme — computed from themeConfig ────────────────────────────────────
//
// Do NOT edit this file to change the look of the app.
// Edit src/theme/themeConfig.ts instead.
//
// This file builds the full AppTheme object from the four config knobs.
// All screens import { appTheme } from here (or use the useAppTheme hook).
//
// ─── 2026 REFRESH (Journey screen polish) ─────────────────────────────────────
//  • Palettes softened: ocean refined, violet → muted lavender,
//    sunrise → muted caramel, NEW rose added.
//  • cardShadow is now NEUTRAL + TIGHT (reads as a crisp edge, not a colored glow).
//  • Added hero.gradient (4-stop) + heroShadow (contained) tokens.
//  • Neutral cool-gray screenBg so white cards separate cleanly.
//  See design_handoff_journey_refresh/README.md for the matching component edits.

import themeConfig, { type PaletteName, type RadiusMode, type DensityMode } from "./themeConfig";
import { fontWeight } from "./tokens";

// ─── Type ─────────────────────────────────────────────────────────────────────

export type AppTheme = {
  /** All color roles used by any screen in the app. */
  colors: {
    // Surfaces
    screenBg:   string;  // main screen background
    cardBg:     string;  // card / panel surface
    inputBg:    string;  // text input background
    modalBg:    string;  // bottom-sheet / modal background

    // Brand accent scale
    accent:      string;  // primary: buttons, active nav, links
    accentDark:  string;  // darker: hero card bg, deep emphasis
    accentLight: string;  // lighter: highlights, icon tints
    accentTint:  string;  // softest: progress tracks, row highlights

    // Text hierarchy
    textPrimary:  string;  // headings, key content
    textBody:     string;  // body copy, descriptions
    textMuted:    string;  // captions, secondary labels
    textDisabled: string;  // locked / inactive

    // Borders & dividers
    border:      string;  // standard card/input border
    borderLight: string;  // subtle internal dividers

    // Semantic status
    success:     string;
    successBg:   string;
    successText: string;
    warning:     string;
    warningBg:   string;
    warningBorder: string;
    warningText: string;
    error:       string;
    errorBg:     string;

    // Streak badge (warm orange — intentionally same across all palettes)
    streakText:   string;
    streakBg:     string;
    streakBorder: string;
  };

  /** Scaled font sizes. Multiply by themeConfig.fontScale. */
  text: {
    display:  number;  // 30 — hero titles, big numbers
    h1:       number;  // 22 — screen-level headings
    h2:       number;  // 18 — section headers
    h3:       number;  // 16 — card titles, prominent labels
    body:     number;  // 16 — primary body text
    bodyMd:   number;  // 14 — secondary body, list items
    caption:  number;  // 12 — captions, metadata
    tiny:     number;  // 10 — badges, chip labels

    // Font weights (pass-through — not palette-dependent)
    weightBlack:     typeof fontWeight.black;
    weightExtrabold: typeof fontWeight.extrabold;
    weightBold:      typeof fontWeight.bold;
    weightSemibold:  typeof fontWeight.semibold;
    weightMedium:    typeof fontWeight.medium;
    weightRegular:   typeof fontWeight.regular;
  };

  /** Density-aware spacing scale. */
  spacing: {
    xs:  number;  //  4 compact /  6 comfortable
    sm:  number;  //  8 / 12
    md:  number;  // 12 / 16
    lg:  number;  // 18 / 24
    xl:  number;  // 24 / 32
    xxl: number;  // 36 / 48
  };

  /** Radius preset chosen by radiusMode. */
  radius: {
    sm:   number;
    md:   number;
    lg:   number;
    xl:   number;
    xxl:  number;
    pill: number;
  };

  // ── Component-level shortcuts ─────────────────────────────────────────────

  /** Hero / continue-learning card. */
  hero: {
    bg:            string;                              // solid fallback bg
    gradient:      [string, string, string, string];   // 4-stop diagonal gradient (use expo-linear-gradient)
    progressFill:  string;
    ctaBg:         string;
    ctaText:       string;
  };

  /** Hero card shadow — contained / tight (not a wide glow). */
  heroShadow: {
    shadowColor:   string;
    shadowOffset:  { width: number; height: number };
    shadowOpacity: number;
    shadowRadius:  number;
    elevation:     number;
  };

  /** Default card shadow — NEUTRAL + TIGHT (crisp edge, not colored glow). */
  cardShadow: {
    shadowColor:   string;
    shadowOffset:  { width: number; height: number };
    shadowOpacity: number;
    shadowRadius:  number;
    elevation:     number;
  };

  /**
   * Four accent colors for the 4-week journey cards.
   * Index: [week1, week2, week3, week4]
   */
  weekColors: [string, string, string, string];

  /** Tab bar / bottom navigation. */
  tabBar: {
    bg:       string;
    active:   string;
    inactive: string;
    border:   string;
  };

  /** Input fields (login, search, etc.). */
  input: {
    bg:          string;
    borderColor: string;
    text:        string;
    placeholder: string;
    radius:      number;
  };

  /** Primary action button. */
  button: {
    bg:     string;
    text:   string;
    radius: number;
  };
};

// ─── Palette definitions ──────────────────────────────────────────────────────

type PaletteColors = Pick<AppTheme["colors"],
  | "accent" | "accentDark" | "accentLight" | "accentTint"
  | "textPrimary" | "textBody"
  | "border" | "borderLight"
> & {
  heroBg:           string;
  heroGradient:     [string, string, string, string];
  heroProgressFill: string;
  heroCtaText:      string;
  weekColors:       [string, string, string, string];
  tabActive:        string;
};

// Shared neutral text + border across every palette (clean, cool-gray system).
const NEUTRALS = {
  textPrimary: "#14132B",
  textBody:    "#3A394F",
  border:      "#ECEBF4",
  borderLight: "#F3F3FA",
};

const PALETTES: Record<PaletteName, PaletteColors> = {
  // Refined teal — the default, fluid and modern.
  ocean: {
    accent:      "#0E9BB8",
    accentDark:  "#0C6F86",
    accentLight: "#2BC4D8",
    accentTint:  "#E4F6FA",
    ...NEUTRALS,
    heroBg:           "#0C6F86",
    heroGradient:     ["#08596B", "#0C7E96", "#119EBC", "#23B6CE"],
    heroProgressFill: "#A9EEF8",
    heroCtaText:      "#0C6F86",
    weekColors:  ["#10B981", "#14B8C4", "#3B9EF0", "#0C7E96"],
    tabActive:   "#0E9BB8",
  },

  // Softened lavender (was the bold deep purple).
  violet: {
    accent:      "#7E6AD6",
    accentDark:  "#574796",
    accentLight: "#A294E4",
    accentTint:  "#EFECFA",
    ...NEUTRALS,
    heroBg:           "#574796",
    heroGradient:     ["#564796", "#6B5BBE", "#8473D6", "#9C8DE4"],
    heroProgressFill: "#DCD3F4",
    heroCtaText:      "#574796",
    weekColors:  ["#4FAE8E", "#5E9BDC", "#9486DD", "#E0A357"],
    tabActive:   "#7E6AD6",
  },

  // Softened caramel (was the fiery amber).
  sunrise: {
    accent:      "#D2873F",
    accentDark:  "#9A5E2C",
    accentLight: "#E6A767",
    accentTint:  "#FBEFE0",
    ...NEUTRALS,
    heroBg:           "#9A5E2C",
    heroGradient:     ["#945A2C", "#B57339", "#D08F4F", "#E3AC6C"],
    heroProgressFill: "#F4DCB8",
    heroCtaText:      "#9A5E2C",
    weekColors:  ["#D2873F", "#4FAE8E", "#5E9BDC", "#C0633F"],
    tabActive:   "#D2873F",
  },

  // NEW — soft warm mauve, human and calm.
  rose: {
    accent:      "#C2647F",
    accentDark:  "#8E4660",
    accentLight: "#D98DA4",
    accentTint:  "#FBECF1",
    ...NEUTRALS,
    heroBg:           "#8E4660",
    heroGradient:     ["#7C3D55", "#9C5470", "#BE7088", "#D38EA3"],
    heroProgressFill: "#F2D2DE",
    heroCtaText:      "#8E4660",
    weekColors:  ["#C2647F", "#5BAE9A", "#6F8AD6", "#E0A357"],
    tabActive:   "#C2647F",
  },
};

// ─── Radius presets ───────────────────────────────────────────────────────────

const RADIUS: Record<RadiusMode, AppTheme["radius"]> = {
  sharp:   { sm: 4,  md: 6,  lg: 8,  xl: 12, xxl: 16, pill: 20    },
  rounded: { sm: 8,  md: 12, lg: 16, xl: 22, xxl: 28, pill: 9999  },
  soft:    { sm: 14, md: 20, lg: 26, xl: 34, xxl: 42, pill: 9999  },
};

// ─── Density / spacing presets ────────────────────────────────────────────────

const SPACING: Record<DensityMode, AppTheme["spacing"]> = {
  compact:     { xs: 4,  sm: 8,  md: 12, lg: 18, xl: 24, xxl: 36 },
  comfortable: { xs: 6,  sm: 12, md: 16, lg: 24, xl: 32, xxl: 48 },
};

// ─── Font size base values (before scale) ─────────────────────────────────────

const BASE_FONT = {
  display: 30,
  h1:      22,
  h2:      18,
  h3:      16,
  body:    16,
  bodyMd:  14,
  caption: 12,
  tiny:    10,
};

function scaleFonts(scale: number): AppTheme["text"] {
  const s = (n: number) => Math.round(n * scale);
  return {
    display:  s(BASE_FONT.display),
    h1:       s(BASE_FONT.h1),
    h2:       s(BASE_FONT.h2),
    h3:       s(BASE_FONT.h3),
    body:     s(BASE_FONT.body),
    bodyMd:   s(BASE_FONT.bodyMd),
    caption:  s(BASE_FONT.caption),
    tiny:     s(BASE_FONT.tiny),
    weightBlack:     fontWeight.black,
    weightExtrabold: fontWeight.extrabold,
    weightBold:      fontWeight.bold,
    weightSemibold:  fontWeight.semibold,
    weightMedium:    fontWeight.medium,
    weightRegular:   fontWeight.regular,
  };
}

// ─── Theme builder ────────────────────────────────────────────────────────────

function buildTheme(config: typeof themeConfig): AppTheme {
  const p = PALETTES[config.palette];
  const r = RADIUS[config.radiusMode];
  const sp = SPACING[config.density];
  const t = scaleFonts(config.fontScale);

  return {
    colors: {
      // Subtle cool-gray app background so white cards separate cleanly.
      screenBg:   "#F4F4FA",
      cardBg:     "#FFFFFF",
      inputBg:    "#F6F6FC",
      modalBg:    "#FFFFFF",

      accent:      p.accent,
      accentDark:  p.accentDark,
      accentLight: p.accentLight,
      accentTint:  p.accentTint,

      textPrimary:  p.textPrimary,
      textBody:     p.textBody,
      textMuted:    "#6B6A85",
      textDisabled: "#A9A8BE",

      border:      p.border,
      borderLight: p.borderLight,

      success:     "#059669",
      successBg:   "#D1FAE5",
      successText: "#065F46",
      warning:     "#D97706",
      warningBg:   "#FFF7ED",
      warningBorder: "#FED7AA",
      warningText: "#92400E",
      error:       "#DC2626",
      errorBg:     "#FEE2E2",

      // Streak stays warm orange regardless of palette
      streakText:   "#EA580C",
      streakBg:     "#FFF7ED",
      streakBorder: "#FED7AA",
    },

    text: t,

    spacing: sp,

    radius: r,

    hero: {
      bg:           p.heroBg,
      gradient:     p.heroGradient,
      progressFill: p.heroProgressFill,
      ctaBg:        "#FFFFFF",
      ctaText:      p.heroCtaText,
    },

    // Contained hero shadow (tight, not a wide spread).
    heroShadow: {
      shadowColor:   p.accentDark,
      shadowOffset:  { width: 0, height: 10 },
      shadowOpacity: 0.22,
      shadowRadius:  18,
      elevation:     6,
    },

    // Neutral + tight — behaves like a crisp edge rather than a colored glow.
    cardShadow: {
      shadowColor:   "#141327",
      shadowOffset:  { width: 0, height: 4 },
      shadowOpacity: 0.10,
      shadowRadius:  10,
      elevation:     2,
    },

    weekColors: p.weekColors,

    tabBar: {
      bg:       "#FFFFFF",
      active:   p.tabActive,
      inactive: "#A9A8BE",
      border:   p.border,
    },

    input: {
      bg:          "#F6F6FC",
      borderColor: p.border,
      text:        p.textPrimary,
      placeholder: "#A9A8BE",
      radius:      r.lg,
    },

    button: {
      bg:     p.accent,
      text:   "#FFFFFF",
      radius: r.lg,
    },
  };
}

// ─── Exported theme & helper ──────────────────────────────────────────────────

/** The fully-computed app theme. Import this in screens + StyleSheets. */
export const appTheme: AppTheme = buildTheme(themeConfig);

/**
 * Re-build with a different config at runtime (e.g. for previewing themes).
 * Most code should just use the static `appTheme` above.
 */
export { buildTheme };
