// ─── App Theme — computed from themeConfig ────────────────────────────────────
//
// Do NOT edit this file to change the look of the app.
// Edit src/theme/themeConfig.ts instead.
//
// This file builds the full AppTheme object from the four config knobs.
// All screens import { appTheme } from here (or use the useAppTheme hook).

import themeConfig, { type PaletteName, type RadiusMode, type DensityMode } from "./themeConfig";
import { fontWeight } from "./tokens";

// ─── Type ─────────────────────────────────────────────────────────────────────

export type AppTheme = {
  /** All color roles used by any screen in the app. */
  colors: {
    // Surfaces
    screenBg:   string;  // main screen background
    cardBg:     string;  // card / panel surface
    inputBg:    string;  // text input background
    modalBg:    string;  // bottom-sheet / modal background

    // Brand accent scale
    accent:      string;  // primary: buttons, active nav, links
    accentDark:  string;  // darker: hero card bg, deep emphasis
    accentLight: string;  // lighter: highlights, icon tints
    accentTint:  string;  // softest: progress tracks, row highlights

    // Text hierarchy
    textPrimary:  string;  // headings, key content
    textBody:     string;  // body copy, descriptions
    textMuted:    string;  // captions, secondary labels
    textDisabled: string;  // locked / inactive

    // Borders & dividers
    border:      string;  // standard card/input border
    borderLight: string;  // subtle internal dividers

    // Semantic status
    success:     string;
    successBg:   string;
    successText: string;
    warning:     string;
    warningBg:   string;
    warningBorder: string;
    warningText: string;
    error:       string;
    errorBg:     string;

    // Streak badge (warm orange — intentionally same across all palettes)
    streakText:   string;
    streakBg:     string;
    streakBorder: string;
  };

  /** Scaled font sizes. Multiply by themeConfig.fontScale. */
  text: {
    display:  number;  // 30 — hero titles, big numbers
    h1:       number;  // 22 — screen-level headings
    h2:       number;  // 18 — section headers
    h3:       number;  // 16 — card titles, prominent labels
    body:     number;  // 16 — primary body text
    bodyMd:   number;  // 14 — secondary body, list items
    caption:  number;  // 12 — captions, metadata
    tiny:     number;  // 10 — badges, chip labels

    // Font weights (pass-through — not palette-dependent)
    weightBlack:     typeof fontWeight.black;
    weightExtrabold: typeof fontWeight.extrabold;
    weightBold:      typeof fontWeight.bold;
    weightSemibold:  typeof fontWeight.semibold;
    weightMedium:    typeof fontWeight.medium;
    weightRegular:   typeof fontWeight.regular;
  };

  /** Density-aware spacing scale. */
  spacing: {
    xs:  number;  //  4 compact /  6 comfortable
    sm:  number;  //  8 / 12
    md:  number;  // 12 / 16
    lg:  number;  // 18 / 24
    xl:  number;  // 24 / 32
    xxl: number;  // 36 / 48
  };

  /** Radius preset chosen by radiusMode. */
  radius: {
    sm:   number;
    md:   number;
    lg:   number;
    xl:   number;
    xxl:  number;
    pill: number;
  };

  // ── Component-level shortcuts ─────────────────────────────────────────────

  /** Hero / continue-learning card. */
  hero: {
    bg:            string;
    progressFill:  string;
    ctaBg:         string;
    ctaText:       string;
  };

  /** Default card shadow (accent-colored, subtle). */
  cardShadow: {
    shadowColor:   string;
    shadowOffset:  { width: number; height: number };
    shadowOpacity: number;
    shadowRadius:  number;
    elevation:     number;
  };

  /**
   * Four accent colors for the 4-week journey cards.
   * Index: [week1, week2, week3, week4]
   */
  weekColors: [string, string, string, string];

  /** Tab bar / bottom navigation. */
  tabBar: {
    bg:       string;
    active:   string;
    inactive: string;
    border:   string;
  };

  /** Input fields (login, search, etc.). */
  input: {
    bg:          string;
    borderColor: string;
    text:        string;
    placeholder: string;
    radius:      number;
  };

  /** Primary action button. */
  button: {
    bg:     string;
    text:   string;
    radius: number;
  };
};

// ─── Palette definitions ──────────────────────────────────────────────────────

type PaletteColors = Pick<AppTheme["colors"],
  | "accent" | "accentDark" | "accentLight" | "accentTint"
  | "textPrimary" | "textBody"
  | "border" | "borderLight"
> & {
  heroBg:           string;
  heroProgressFill: string;
  heroCtaText:      string;
  weekColors:       [string, string, string, string];
  tabActive:        string;
};

const PALETTES: Record<PaletteName, PaletteColors> = {
  ocean: {
    accent:      "#0891B2",
    accentDark:  "#0E7490",
    accentLight: "#06B6D4",
    accentTint:  "#EBF7FA",
    textPrimary: "#0F172A",
    textBody:    "#334155",
    border:      "#D8EEF4",
    borderLight: "#EBF7FA",
    heroBg:           "#0E7490",
    heroProgressFill: "#A5F3FC",
    heroCtaText:      "#0E7490",
    weekColors:  ["#0891B2", "#14B8A6", "#0EA5E9", "#0E7490"],
    tabActive:   "#0891B2",
  },

  violet: {
    accent:      "#6C3CE1",
    accentDark:  "#4C1D95",
    accentLight: "#8B5CF6",
    accentTint:  "#EDE9FE",
    textPrimary: "#1E1B4B",
    textBody:    "#374151",
    border:      "#DDD6FE",
    borderLight: "#EDE9FE",
    heroBg:           "#4C1D95",
    heroProgressFill: "#C4B5FD",
    heroCtaText:      "#4C1D95",
    weekColors:  ["#6C3CE1", "#8B5CF6", "#0D9488", "#4C1D95"],
    tabActive:   "#6C3CE1",
  },

  sunrise: {
    accent:      "#D97706",
    accentDark:  "#92400E",
    accentLight: "#F59E0B",
    accentTint:  "#FEF3C7",
    textPrimary: "#1C1917",
    textBody:    "#44403C",
    border:      "#FDE68A",
    borderLight: "#FEF3C7",
    heroBg:           "#92400E",
    heroProgressFill: "#FDE68A",
    heroCtaText:      "#92400E",
    weekColors:  ["#D97706", "#0D9488", "#0EA5E9", "#92400E"],
    tabActive:   "#D97706",
  },
};

// ─── Radius presets ───────────────────────────────────────────────────────────

const RADIUS: Record<RadiusMode, AppTheme["radius"]> = {
  sharp:   { sm: 4,  md: 6,  lg: 8,  xl: 12, xxl: 16, pill: 20    },
  rounded: { sm: 8,  md: 12, lg: 16, xl: 22, xxl: 28, pill: 9999  },
  soft:    { sm: 14, md: 20, lg: 26, xl: 34, xxl: 42, pill: 9999  },
};

// ─── Density / spacing presets ────────────────────────────────────────────────

const SPACING: Record<DensityMode, AppTheme["spacing"]> = {
  compact:     { xs: 4,  sm: 8,  md: 12, lg: 18, xl: 24, xxl: 36 },
  comfortable: { xs: 6,  sm: 12, md: 16, lg: 24, xl: 32, xxl: 48 },
};

// ─── Font size base values (before scale) ─────────────────────────────────────

const BASE_FONT = {
  display: 30,
  h1:      22,
  h2:      18,
  h3:      16,
  body:    16,
  bodyMd:  14,
  caption: 12,
  tiny:    10,
};

function scaleFonts(scale: number): AppTheme["text"] {
  const s = (n: number) => Math.round(n * scale);
  return {
    display:  s(BASE_FONT.display),
    h1:       s(BASE_FONT.h1),
    h2:       s(BASE_FONT.h2),
    h3:       s(BASE_FONT.h3),
    body:     s(BASE_FONT.body),
    bodyMd:   s(BASE_FONT.bodyMd),
    caption:  s(BASE_FONT.caption),
    tiny:     s(BASE_FONT.tiny),
    weightBlack:     fontWeight.black,
    weightExtrabold: fontWeight.extrabold,
    weightBold:      fontWeight.bold,
    weightSemibold:  fontWeight.semibold,
    weightMedium:    fontWeight.medium,
    weightRegular:   fontWeight.regular,
  };
}

// ─── Theme builder ────────────────────────────────────────────────────────────

function buildTheme(config: typeof themeConfig): AppTheme {
  const p = PALETTES[config.palette];
  const r = RADIUS[config.radiusMode];
  const sp = SPACING[config.density];
  const t = scaleFonts(config.fontScale);

  return {
    colors: {
      screenBg:   "#FFFFFF",
      cardBg:     "#FFFFFF",
      inputBg:    "#F8FAFC",
      modalBg:    "#FFFFFF",

      accent:      p.accent,
      accentDark:  p.accentDark,
      accentLight: p.accentLight,
      accentTint:  p.accentTint,

      textPrimary:  p.textPrimary,
      textBody:     p.textBody,
      textMuted:    "#64748B",
      textDisabled: "#94A3B8",

      border:      p.border,
      borderLight: p.borderLight,

      success:     "#059669",
      successBg:   "#D1FAE5",
      successText: "#065F46",
      warning:     "#D97706",
      warningBg:   "#FFF7ED",
      warningBorder: "#FED7AA",
      warningText: "#92400E",
      error:       "#DC2626",
      errorBg:     "#FEE2E2",

      // Streak stays warm orange regardless of palette
      streakText:   "#EA580C",
      streakBg:     "#FFF7ED",
      streakBorder: "#FED7AA",
    },

    text: t,

    spacing: sp,

    radius: r,

    hero: {
      bg:           p.heroBg,
      progressFill: p.heroProgressFill,
      ctaBg:        "#FFFFFF",
      ctaText:      p.heroCtaText,
    },

    cardShadow: {
      shadowColor:   p.accentLight,
      shadowOffset:  { width: 0, height: 4 },
      shadowOpacity: 0.14,
      shadowRadius:  14,
      elevation:     4,
    },

    weekColors: p.weekColors,

    tabBar: {
      bg:       "#FFFFFF",
      active:   p.tabActive,
      inactive: "#94A3B8",
      border:   p.border,
    },

    input: {
      bg:          "#F8FAFC",
      borderColor: p.border,
      text:        p.textPrimary,
      placeholder: "#94A3B8",
      radius:      r.lg,
    },

    button: {
      bg:     p.accent,
      text:   "#FFFFFF",
      radius: r.lg,
    },
  };
}

// ─── Exported theme & helper ──────────────────────────────────────────────────

/** The fully-computed app theme. Import this in screens + StyleSheets. */
export const appTheme: AppTheme = buildTheme(themeConfig);

/**
 * Re-build with a different config at runtime (e.g. for previewing themes).
 * Most code should just use the static `appTheme` above.
 */
export { buildTheme };
