#!/usr/bin/env python3
"""
build_seed.py — turn a validated lesson JSON into a REVIEWABLE Supabase seed
.sql file (preview). It validates first; it never touches the database.

Workflow:  author JSON  →  validate_lesson.py  →  build_seed.py  →  review  →  approve  →  apply with service key

Usage:
    python3 build_seed.py lesson.json \
        --program ai_for_everyone --unit-order 1 --unit-label "Day 1" \
        --unit-title "What AI Is" --lesson-order 1 --lesson-title "Your First Question" \
        --minutes 12 --out 00NN_seed_lesson.sql

The lesson.json may be {"meta": {...}, "steps": [...]} or a bare steps array;
CLI flags override meta. Programs/units are upserted idempotently by natural key.
"""
import sys, json, argparse, pathlib
from validate_lesson import validate, is_list

def sql_str(x):  # safe single-quote escaping
    return "'" + str(x).replace("'", "''") + "'"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("lesson")
    ap.add_argument("--program", required=True)
    ap.add_argument("--unit-order", type=int, required=True)
    ap.add_argument("--unit-label", default=None)
    ap.add_argument("--unit-title", required=True)
    ap.add_argument("--unit-theme", default="")
    ap.add_argument("--lesson-order", type=int, default=1)
    ap.add_argument("--lesson-title", required=True)
    ap.add_argument("--minutes", type=int, default=10)
    ap.add_argument("--out", default="seed_preview.sql")
    a = ap.parse_args()

    data = json.load(open(a.lesson))
    steps = data["steps"] if isinstance(data, dict) and "steps" in data else data
    if not is_list(steps):
        print("ERROR: no steps array"); sys.exit(1)

    errors, warnings = validate(steps)
    for w in warnings: print(f"  WARN  {w}")
    if errors:
        for e in errors: print(f"  ERROR {e}")
        print("\nRefusing to build seed — fix errors first."); sys.exit(1)

    steps_json = json.dumps(steps, ensure_ascii=False, indent=2)
    label = a.unit_label or f"Unit {a.unit_order}"

    sql = f"""-- PREVIEW SEED — review & approve before applying with the service key.
-- Program: {a.program}  Unit {a.unit_order} ({label})  Lesson {a.lesson_order}
-- Generated by build_seed.py after passing validate_lesson.py.

insert into units (program_id, order_num, label, title, theme)
select id, {a.unit_order}, {sql_str(label)}, {sql_str(a.unit_title)}, {sql_str(a.unit_theme)}
from programs where slug = {sql_str(a.program)}
on conflict (program_id, order_num) do nothing;

insert into lessons (unit_id, order_num, title, est_minutes, steps)
select u.id, {a.lesson_order}, {sql_str(a.lesson_title)}, {a.minutes}, $json${steps_json}$json$::jsonb
from units u join programs p on p.id = u.program_id
where p.slug = {sql_str(a.program)} and u.order_num = {a.unit_order}
on conflict (unit_id, order_num) do nothing;
"""
    pathlib.Path(a.out).write_text(sql)
    print(f"\nOK — {len(steps)} steps → {a.out}  (preview only; not applied)")

if __name__ == "__main__":
    main()
