-- PREVIEW SEED — review & approve before applying with the service key.
-- Program: ai_for_everyone  Unit 3 (Day 3)  Lesson 1
-- Generated by build_seed.py after passing validate_lesson.py.

insert into programs (slug, title, subtitle, unit_label, artifact_label)
values ('ai_for_everyone', 'AI for Everyone', '28 days to AI confidence', 'Day', 'Artifact')
on conflict (slug) do nothing;

insert into units (program_id, order_num, label, title, theme)
select id, 3, 'Day 3', 'Asking AI to Write and Rewrite', ''
from programs where slug = 'ai_for_everyone'
on conflict (program_id, order_num) do nothing;

insert into lessons (unit_id, order_num, title, est_minutes, steps)
select u.id, 1, 'Your Personal Writing Assistant', 13, $json$[
  {
    "id": "d3_s1",
    "type": "info",
    "title": "Welcome to Day 3",
    "body": "One of the most useful everyday skills: asking AI to write something for you — then asking it to rewrite it until it is right.",
    "audioUrl": null,
    "primaryButton": "Let's write",
    "xp": 3
  },
  {
    "id": "d3_s2",
    "type": "example",
    "title": "Start with a rough idea",
    "prompt": "Write a polite email to my landlord asking if I can extend my lease by three months. I have been a good tenant for two years and always pay on time. Keep it friendly and respectful.",
    "primaryButton": "Good example",
    "xp": 3
  },
  {
    "id": "d3_s3",
    "type": "info",
    "title": "Iteration is the real skill",
    "body": "Rarely is the first draft perfect. The skill is asking for revisions: 'Make it shorter', 'Make it friendlier', 'Add a reminder about the security deposit.' AI never gets annoyed by revisions.",
    "audioUrl": null,
    "primaryButton": "Teach me",
    "xp": 3
  },
  {
    "id": "d3_s4",
    "type": "scenario_card",
    "title": "Imagine this",
    "body": "You wrote a text message to a coworker, but it sounds harsh. You paste it into AI and ask: 'Rewrite this to sound warmer but still professional.' It comes back perfect in seconds.",
    "audioUrl": null,
    "primaryButton": "That would be useful",
    "xp": 3
  },
  {
    "id": "d3_s5",
    "type": "mc",
    "title": "Best first step?",
    "question": "You need a cover letter for a job. What should you ask AI first?",
    "options": [
      "Write me a perfect cover letter.",
      "Write a draft cover letter for a customer support role. I have 5 years experience. Make it concise."
    ],
    "correct": 1,
    "feedback": [
      "That is too vague — AI will write something generic.",
      "Yes. Give your role, experience, and preferred style upfront."
    ],
    "xp": 10
  },
  {
    "id": "d3_s6",
    "type": "highlight",
    "title": "Find the revision instructions",
    "body": "After the first draft, you say: 'Make this shorter by removing the second paragraph. Change the tone to more casual. Add a sentence about my interest in learning new tools.'",
    "highlights": [
      "Make this shorter by removing the second paragraph",
      "Change the tone to more casual",
      "Add a sentence about my interest in learning new tools"
    ],
    "xp": 6
  },
  {
    "id": "d3_s7",
    "type": "tf",
    "title": "True or false?",
    "question": "If AI's first draft is not what you wanted, you should rewrite it yourself from scratch.",
    "correct": false,
    "feedback": [
      "Not the most efficient path — asking AI to revise is faster.",
      "Right. You can ask for changes: shorter, longer, friendlier, more formal."
    ],
    "xp": 5
  },
  {
    "id": "d3_s8",
    "type": "good_fit",
    "title": "Good fit?",
    "question": "Write a thoughtful birthday message for my best friend who loves hiking and photography.",
    "correct": "good",
    "feedback": [
      "Yes. Context about the person helps AI personalize the message.",
      "Right. AI can write a warm message when you describe the person."
    ],
    "xp": 5
  },
  {
    "id": "d3_s9a",
    "type": "info",
    "title": "But not for everything",
    "body": "AI can write almost anything, but some things need a human expert. Let us check if you can spot the boundary.",
    "audioUrl": null,
    "primaryButton": "I see",
    "xp": 3
  },
  {
    "id": "d3_s9",
    "type": "good_fit",
    "title": "Good fit?",
    "question": "Write a legally binding contract for selling my car.",
    "correct": "notideal",
    "feedback": [
      "Be careful — legal documents need a real lawyer.",
      "Right. For important legal matters, AI is a starting point, not the final word."
    ],
    "xp": 5
  },
  {
    "id": "d3_s10",
    "type": "info",
    "title": "Four useful revision commands",
    "body": "These four commands cover most needs:\n\n1. 'Make this shorter/longer'\n2. 'Change the tone to [friendly/professional/urgent]'\n3. 'Rewrite for a different audience'\n4. 'Fix the grammar and spelling'",
    "audioUrl": null,
    "primaryButton": "Save these",
    "xp": 3
  },
  {
    "id": "d3_s11",
    "type": "builder",
    "title": "Build a writing prompt",
    "fields": [
      {
        "id": "topic",
        "label": "What do you need AI to write?",
        "placeholder": "a thank-you note after a job interview"
      },
      {
        "id": "audience",
        "label": "Who is reading this?",
        "placeholder": "the hiring manager I just met"
      },
      {
        "id": "tone",
        "label": "What tone should it have?",
        "placeholder": "warm, professional, grateful"
      }
    ],
    "template": "Write {{topic}} for {{audience}}. Use a {{tone}} tone.",
    "primaryButton": "Generate draft",
    "xp": 15
  },
  {
    "id": "d3_s12",
    "type": "copy_action",
    "title": "Copy and use it",
    "body": "Copy your prompt and paste it into an AI tool. See what the first draft looks like.",
    "sourceStepId": "d3_s11",
    "primaryButton": "I copied it",
    "xp": 5
  },
  {
    "id": "d3_s13",
    "type": "paste_capture",
    "title": "Paste the first draft",
    "body": "Paste what AI wrote. We will keep it in your work history.",
    "minLength": 20,
    "primaryButton": "Submit draft",
    "xp": 10
  },
  {
    "id": "d3_s14",
    "type": "info",
    "title": "Now revise it",
    "body": "Now take that draft and ask AI to improve it. Try: 'Make this shorter by half' or 'Make it sound more enthusiastic.' See how the revision changes.",
    "audioUrl": null,
    "primaryButton": "I will try it",
    "xp": 3
  },
  {
    "id": "d3_s15",
    "type": "paste_capture",
    "title": "Paste the revised version",
    "body": "Paste the revised version here. Compare it with the first draft in your work history.",
    "minLength": 20,
    "primaryButton": "Submit revision",
    "xp": 10
  },
  {
    "id": "d3_s16",
    "type": "reflection",
    "title": "Compare the drafts",
    "questions": [
      {
        "id": "improvement",
        "type": "single_choice",
        "label": "Was the revised version better than the first?",
        "options": [
          "Much better",
          "Slightly better",
          "About the same",
          "Worse"
        ]
      },
      {
        "id": "what_changed",
        "type": "textarea",
        "label": "What specific revision would you ask for next?"
      }
    ],
    "xp": 10
  },
  {
    "id": "d3_s17",
    "type": "fillblank",
    "title": "Fill in the blank",
    "question": "If AI's first draft is not right, you ask for a ______ instead of starting over.",
    "answer": "revision",
    "aliases": [
      "rewrite",
      "edit",
      "change",
      "version"
    ],
    "feedback": [
      "Exactly. Asking for a revision keeps the good parts and fixes the rest.",
      "Close. The key idea: ask AI to revise, not start from scratch."
    ],
    "xp": 5
  },
  {
    "id": "d3_s18",
    "type": "match",
    "title": "Match the need to the command",
    "pairs": [
      {
        "left": "Too long",
        "right": "Make this shorter"
      },
      {
        "left": "Sounds rude",
        "right": "Change the tone to friendly"
      },
      {
        "left": "Full of typos",
        "right": "Fix the grammar and spelling"
      }
    ],
    "xp": 12
  },
  {
    "id": "d3_s19",
    "type": "quiz",
    "title": "Quick mastery check",
    "questions": [
      {
        "id": "q1",
        "type": "mc",
        "question": "When the first AI draft is not right, what should you do?",
        "options": [
          "Give up on AI",
          "Ask AI to revise with specific instructions",
          "Use a different AI tool"
        ],
        "correct": 1
      },
      {
        "id": "q2",
        "type": "mc",
        "question": "Which of these is most helpful before asking AI to write?",
        "options": [
          "A general topic",
          "The audience and tone you want",
          "A one-word instruction"
        ],
        "correct": 1
      },
      {
        "id": "q3",
        "type": "tf",
        "question": "AI-generated legal documents are always safe to use without a lawyer.",
        "correct": false
      }
    ],
    "xp": 15
  },
  {
    "id": "d3_s20",
    "type": "badge_unlock",
    "badgeSlug": "writing_ally"
  },
  {
    "id": "d3_s21",
    "type": "completion",
    "title": "Day 3 complete",
    "body": "You can now use AI to draft anything — emails, messages, notes — and revise it until it is right. Writing with AI is a conversation, not a one-shot command. See you tomorrow.",
    "primaryButton": "Go to my journey"
  }
]$json$::jsonb
from units u join programs p on p.id = u.program_id
where p.slug = 'ai_for_everyone' and u.order_num = 3
on conflict (unit_id, order_num) do nothing;
