-- PREVIEW SEED — review & approve before applying with the service key.
-- Program: ai_for_everyone  Unit 4 (Day 4)  Lesson 1
-- Generated by build_seed.py after passing validate_lesson.py.

insert into units (program_id, order_num, label, title, theme)
select id, 4, 'Day 4', 'Summarizing, Organizing, and Planning with AI', ''
from programs where slug = 'ai_for_everyone'
on conflict (program_id, order_num) do nothing;

insert into lessons (unit_id, order_num, title, est_minutes, steps)
select u.id, 1, 'Your Brain''s Second Processor', 14, $json$[
  {
    "id": "d4_s1",
    "type": "info",
    "title": "Welcome to Day 4",
    "body": "So far you have asked questions and written drafts. Now you will use AI to digest information and make plans — like having an assistant who reads everything and organizes it for you.",
    "audioUrl": null,
    "primaryButton": "Let's organize",
    "xp": 3
  },
  {
    "id": "d4_s2",
    "type": "example",
    "title": "Summarize anything",
    "prompt": "Summarize this article in 3 bullet points. Use simple language. Focus on the key takeaways a beginner should remember: [paste text]",
    "primaryButton": "That is powerful",
    "xp": 3
  },
  {
    "id": "d4_s3",
    "type": "scenario_card",
    "title": "Imagine this",
    "body": "Your inbox has 50 unread messages from this week. Instead of reading each one individually, you paste them into AI and ask: 'Summarize the most important emails I need to respond to, grouped by urgency.'",
    "audioUrl": null,
    "primaryButton": "That would save hours",
    "xp": 3
  },
  {
    "id": "d4_s4",
    "type": "mc",
    "title": "Best summarize request",
    "question": "Which of these will give the best summary?",
    "options": [
      "Summarize this.",
      "Summarize this article in 5 bullet points. Highlight any numbers or deadlines. Use clear language."
    ],
    "correct": 1,
    "feedback": [
      "Too vague — AI will guess what matters.",
      "Yes. Giving structure (bullet points) and focus (numbers/deadlines) gets a useful summary."
    ],
    "xp": 10
  },
  {
    "id": "d4_s5",
    "type": "tf",
    "title": "True or false?",
    "question": "When asking for a summary, you should tell AI what to focus on and the format you want.",
    "correct": true,
    "feedback": [
      "Think again — the more specific your request, the better the summary.",
      "Correct. 'Focus on the budget changes' or 'Highlight customer complaints' directs AI's attention."
    ],
    "xp": 5
  },
  {
    "id": "d4_s6",
    "type": "highlight",
    "title": "Spot the summary instructions",
    "body": "Extract all action items from these meeting notes. Group them by owner. For each item include: what needs to happen, who is responsible, and the deadline.",
    "highlights": [
      "Extract all action items",
      "Group them by owner",
      "what needs to happen",
      "who is responsible",
      "the deadline"
    ],
    "xp": 6
  },
  {
    "id": "d4_s7",
    "type": "good_fit",
    "title": "Good fit?",
    "question": "Turn this messy list of errands into a sorted, efficient plan organized by location so I waste less time driving.",
    "correct": "good",
    "feedback": [
      "Yes — organizing by location is exactly what AI does well.",
      "Right. AI can reorder and group information efficiently."
    ],
    "xp": 5
  },
  {
    "id": "d4_s8a",
    "type": "info",
    "title": "But some things are yours alone",
    "body": "AI can organize tasks, but some decisions are deeply personal. See if you can tell the difference.",
    "audioUrl": null,
    "primaryButton": "I understand",
    "xp": 3
  },
  {
    "id": "d4_s8",
    "type": "good_fit",
    "title": "Good fit?",
    "question": "Decide for me whether I should break up with my partner.",
    "correct": "notideal",
    "feedback": [
      "That is a deeply personal decision — AI should not make it for you.",
      "Right. AI can list pros and cons, but the decision is yours."
    ],
    "xp": 5
  },
  {
    "id": "d4_s9",
    "type": "info",
    "title": "Planning with AI",
    "body": "AI is great at making plans: weekly schedules, packing lists, renovation timelines, meal plans. Give it the pieces and tell it how to arrange them.",
    "audioUrl": null,
    "primaryButton": "Show me how",
    "xp": 3
  },
  {
    "id": "d4_s10",
    "type": "example",
    "title": "A good planning prompt",
    "prompt": "Help me plan a weekend home project. I need to: paint the living room, fix a leaky faucet, organize the garage. I have Saturday 8am-5pm and Sunday 10am-3pm. I will do it alone. Suggest a realistic schedule with breaks.",
    "primaryButton": "I see the pattern",
    "xp": 3
  },
  {
    "id": "d4_s11",
    "type": "info",
    "title": "Here is the pattern",
    "body": "For planning: 1. List what needs to happen. 2. State your constraints (time, budget, help). 3. Ask for a specific format (schedule, checklist, timeline). 4. Review and adjust.",
    "audioUrl": null,
    "primaryButton": "Got it",
    "xp": 3
  },
  {
    "id": "d4_s12",
    "type": "builder",
    "title": "Build a plan or summary request",
    "fields": [
      {
        "id": "task",
        "label": "What do you need? (summarize, plan, organize)",
        "placeholder": "plan a busy Saturday"
      },
      {
        "id": "raw_material",
        "label": "What information should AI work with?",
        "placeholder": "grocery shopping, laundry, gym, pick up kids at 3pm"
      },
      {
        "id": "format_out",
        "label": "How should the result look?",
        "placeholder": "a timeline sorted by location"
      }
    ],
    "template": "Please {{task}} using this information: {{raw_material}}. Give me the result as {{format_out}}.",
    "primaryButton": "Generate my request",
    "xp": 15
  },
  {
    "id": "d4_s13",
    "type": "copy_action",
    "title": "Copy your request",
    "body": "Copy your prompt and paste it into AI.",
    "sourceStepId": "d4_s12",
    "primaryButton": "I copied it",
    "xp": 5
  },
  {
    "id": "d4_s14",
    "type": "paste_capture",
    "title": "Paste AI's response",
    "body": "Paste what AI created. See how it organized your information.",
    "minLength": 20,
    "primaryButton": "Submit",
    "xp": 10
  },
  {
    "id": "d4_s15",
    "type": "reflection",
    "title": "Rate the organization",
    "questions": [
      {
        "id": "organization",
        "type": "single_choice",
        "label": "How well did AI organize your information?",
        "options": [
          "Very well — better than I could have",
          "Decent — some useful structure",
          "Not great — too generic"
        ]
      },
      {
        "id": "next",
        "type": "textarea",
        "label": "What would you ask AI to organize next?"
      }
    ],
    "xp": 10
  },
  {
    "id": "d4_s16",
    "type": "fillblank",
    "title": "Fill in the blank",
    "question": "A good summary tells AI what to focus on and in what ______.",
    "answer": "format",
    "aliases": [
      "structure",
      "style",
      "way"
    ],
    "feedback": [
      "Exactly. The format (bullets, paragraph, table) makes the summary useful.",
      "Close. The answer is 'format' — tell AI how to structure the result."
    ],
    "xp": 5
  },
  {
    "id": "d4_s17",
    "type": "match",
    "title": "Match the task to the request",
    "pairs": [
      {
        "left": "A long email thread about a project delay",
        "right": "Summarize the key updates and decisions"
      },
      {
        "left": "A refrigerator full of random ingredients",
        "right": "Suggest 3 meals I can make with these items"
      },
      {
        "left": "A messy week with no plan",
        "right": "Create a schedule organized by priority"
      }
    ],
    "xp": 12
  },
  {
    "id": "d4_s18",
    "type": "quiz",
    "title": "Quick mastery check",
    "questions": [
      {
        "id": "q1",
        "type": "mc",
        "question": "What is the most important thing to include in a summarize request?",
        "options": [
          "The word 'please'",
          "What to focus on and what format to use",
          "The name of the AI tool"
        ],
        "correct": 1
      },
      {
        "id": "q2",
        "type": "mc",
        "question": "AI is best at planning when you give it:",
        "options": [
          "Just the goal with no constraints",
          "The list of tasks AND your constraints",
          "Only the deadline"
        ],
        "correct": 1
      },
      {
        "id": "q3",
        "type": "tf",
        "question": "AI is a good tool for listing pros and cons, but the final decision should be yours.",
        "correct": true
      }
    ],
    "xp": 15
  },
  {
    "id": "d4_s19",
    "type": "badge_unlock",
    "badgeSlug": "info_master"
  },
  {
    "id": "d4_s20",
    "type": "completion",
    "title": "Day 4 complete",
    "body": "You now know how to use AI to summarize, organize, and plan. These skills turn AI into a personal assistant that processes information and builds structure. See you tomorrow.",
    "primaryButton": "Go to my journey"
  }
]$json$::jsonb
from units u join programs p on p.id = u.program_id
where p.slug = 'ai_for_everyone' and u.order_num = 4
on conflict (unit_id, order_num) do nothing;
