-- PREVIEW SEED — review & approve before applying with the service key.
-- Program: ai_for_everyone  Unit 6 (Day 6)  Lesson 1
-- Generated by build_seed.py after passing validate_lesson.py.

insert into programs (slug, title, subtitle, unit_label, artifact_label)
values ('ai_for_everyone', 'AI for Everyone', '28 days to AI confidence', 'Day', 'Artifact')
on conflict (slug) do nothing;

insert into units (program_id, order_num, label, title, theme)
select id, 6, 'Day 6', 'Creative Brainstorming and Problem-Solving', ''
from programs where slug = 'ai_for_everyone'
on conflict (program_id, order_num) do nothing;

insert into lessons (unit_id, order_num, title, est_minutes, steps)
select u.id, 1, 'Your Infinite Idea Partner', 13, $json$[
  {
    "id": "d6_s1",
    "type": "info",
    "title": "Welcome to Day 6",
    "body": "Today you will use AI as a creative partner. Stuck on a problem? Need gift ideas? Planning a party? AI can generate more ideas than you can on your own.",
    "audioUrl": null,
    "primaryButton": "Let's create",
    "xp": 3
  },
  {
    "id": "d6_s2",
    "type": "scenario_card",
    "title": "Picture this",
    "body": "You need to plan a birthday party for a friend who loves cooking, jazz music, and hiking. You are out of ideas after two suggestions. AI gives you 15 creative party themes in seconds.",
    "audioUrl": null,
    "primaryButton": "That is brilliant",
    "xp": 3
  },
  {
    "id": "d6_s3",
    "type": "info",
    "title": "How brainstorming with AI works",
    "body": "1. Describe the challenge. 2. Give constraints (budget, time, audience). 3. Ask for many ideas. 4. Pick the ones you like. 5. Ask AI to expand on the best one.",
    "audioUrl": null,
    "primaryButton": "Simple enough",
    "xp": 3
  },
  {
    "id": "d6_s4",
    "type": "example",
    "title": "A great brainstorm prompt",
    "prompt": "I need gift ideas for my dad. He is 62, loves gardening, woodworking, and jazz. Budget is $50. Give me 10 ideas, from practical to creative. Tell me why each one would work.",
    "primaryButton": "This is a goldmine",
    "xp": 3
  },
  {
    "id": "d6_s5",
    "type": "mc",
    "title": "Which gets the best ideas?",
    "question": "Which prompt will generate the most useful ideas?",
    "options": [
      "Give me ideas for dinner.",
      "I have chicken, rice, broccoli, and 30 minutes. Give me 5 dinner ideas from different cuisines (Italian, Asian, Mexican)."
    ],
    "correct": 1,
    "feedback": [
      "Too open-ended — AI will list obvious things.",
      "Yes. Ingredients, time, and variety make AI's ideas relevant and creative."
    ],
    "xp": 10
  },
  {
    "id": "d6_s6",
    "type": "good_fit",
    "title": "Good fit?",
    "question": "Suggest 10 names for my new coffee shop. It is cozy, vintage-themed, and near a university.",
    "correct": "good",
    "feedback": [
      "Yes. The theme, audience, and quantity give AI direction.",
      "Right. AI is great at generating many options from a creative brief."
    ],
    "xp": 5
  },
  {
    "id": "d6_s7a",
    "type": "info",
    "title": "But not for personal disputes",
    "body": "AI can suggest compromises, but personal conflicts need real conversation. Let us check your intuition about boundaries.",
    "audioUrl": null,
    "primaryButton": "Got it",
    "xp": 3
  },
  {
    "id": "d6_s7",
    "type": "good_fit",
    "title": "Good fit?",
    "question": "Solve this: my sister and I disagree about who should host Thanksgiving. Decide who is right.",
    "correct": "notideal",
    "feedback": [
      "AI cannot resolve family disputes — it does not know your relationship.",
      "Exactly. AI can suggest compromises, but decisions about personal conflicts are yours."
    ],
    "xp": 5
  },
  {
    "id": "d6_s8",
    "type": "highlight",
    "title": "Find the creative constraints",
    "body": "Suggest 5 social media post ideas for my small bakery. We specialize in gluten-free cakes. Target audience is health-conscious women aged 25-40. Tone should be warm and encouraging. Each post should have a caption idea.",
    "highlights": [
      "small bakery",
      "gluten-free cakes",
      "health-conscious women aged 25-40",
      "warm and encouraging",
      "caption idea"
    ],
    "xp": 6
  },
  {
    "id": "d6_s9",
    "type": "tf",
    "title": "True or false?",
    "question": "When brainstorming with AI, asking for more ideas (10-15) gives you more to choose from than asking for 2-3.",
    "correct": true,
    "feedback": [
      "Correct. Quantity helps — you can pick the best and discard the rest.",
      "Yes. Ask for many ideas, then refine the ones that stand out."
    ],
    "xp": 5
  },
  {
    "id": "d6_s10",
    "type": "info",
    "title": "The expand technique",
    "body": "Once AI gives you ideas, pick your favorite and ask: 'Expand on idea #3. Give me a step-by-step plan for making it happen.' This turns brainstorming into action.",
    "audioUrl": null,
    "primaryButton": "I will use this",
    "xp": 3
  },
  {
    "id": "d6_s11",
    "type": "example",
    "title": "From idea to plan",
    "prompt": "Expand on the 'weekend brunch meal prep' idea. Give me a shopping list, a schedule for Saturday morning, and 3 recipes that use the same ingredients.",
    "primaryButton": "Going from idea to plan",
    "xp": 3
  },
  {
    "id": "d6_s12",
    "type": "builder",
    "title": "Build a brainstorm prompt",
    "fields": [
      {
        "id": "challenge",
        "label": "What do you need ideas for?",
        "placeholder": "a creative date night on a $30 budget"
      },
      {
        "id": "constraints",
        "label": "What constraints or preferences matter?",
        "placeholder": "inside the city, no car, vegetarian, evening"
      },
      {
        "id": "quantity",
        "label": "How many ideas do you want?",
        "placeholder": "10 options"
      }
    ],
    "template": "I need ideas for {{challenge}}. Constraints: {{constraints}}. Give me {{quantity}}. For each idea, explain why it works.",
    "primaryButton": "Generate ideas",
    "xp": 15
  },
  {
    "id": "d6_s13",
    "type": "copy_action",
    "title": "Copy your brainstorm",
    "body": "Copy your prompt and paste it into an AI tool.",
    "sourceStepId": "d6_s12",
    "primaryButton": "I copied it",
    "xp": 5
  },
  {
    "id": "d6_s14",
    "type": "paste_capture",
    "title": "Paste the ideas",
    "body": "Paste the ideas AI generated. Which one is your favorite?",
    "minLength": 20,
    "primaryButton": "Submit ideas",
    "xp": 10
  },
  {
    "id": "d6_s15",
    "type": "reflection",
    "title": "Which idea stands out?",
    "questions": [
      {
        "id": "best_idea",
        "type": "single_choice",
        "label": "How many useful ideas did AI give you?",
        "options": [
          "5 or more usable ideas",
          "2-4 usable ideas",
          "1 or none"
        ]
      },
      {
        "id": "surprise",
        "type": "textarea",
        "label": "Was there an idea you would not have thought of? What was it?"
      }
    ],
    "xp": 10
  },
  {
    "id": "d6_s16",
    "type": "fillblank",
    "title": "Fill in the blank",
    "question": "After AI gives you ideas, you can ask it to ______ on the best one with a full plan.",
    "answer": "expand",
    "aliases": [
      "elaborate",
      "detail",
      "develop",
      "extend"
    ],
    "feedback": [
      "Exactly. 'Expand on idea #3' turns a suggestion into a plan.",
      "Close. The word is 'expand' — ask AI to flesh out the best idea."
    ],
    "xp": 5
  },
  {
    "id": "d6_s17",
    "type": "match",
    "title": "Match the situation to the strategy",
    "pairs": [
      {
        "left": "You need gift ideas",
        "right": "Describe the person and your budget"
      },
      {
        "left": "AI gave you 10 ideas, one is great",
        "right": "Ask AI to expand on that specific idea"
      },
      {
        "left": "You have limited ingredients for dinner",
        "right": "List what you have and ask for recipes"
      }
    ],
    "xp": 12
  },
  {
    "id": "d6_s18",
    "type": "quiz",
    "title": "Quick mastery check",
    "questions": [
      {
        "id": "q1",
        "type": "mc",
        "question": "For the best brainstorming results, what should you include?",
        "options": [
          "Only the topic",
          "The topic, constraints, and how many ideas you want",
          "A demand for perfect ideas only"
        ],
        "correct": 1
      },
      {
        "id": "q2",
        "type": "mc",
        "question": "After AI gives you ideas, what is the next step?",
        "options": [
          "Use the first one without changes",
          "Pick the best and ask AI to expand it into a plan",
          "Discard all of them and start over"
        ],
        "correct": 1
      },
      {
        "id": "q3",
        "type": "tf",
        "question": "AI should make final decisions about personal conflicts for you.",
        "correct": false
      }
    ],
    "xp": 15
  },
  {
    "id": "d6_s19",
    "type": "badge_unlock",
    "badgeSlug": "idea_machine"
  },
  {
    "id": "d6_s20",
    "type": "completion",
    "title": "Day 6 complete",
    "body": "You now have an infinite brainstorming partner. Give it constraints, ask for many ideas, pick the best, then expand. Creativity on demand. See you tomorrow for the final day.",
    "primaryButton": "Go to my journey"
  }
]$json$::jsonb
from units u join programs p on p.id = u.program_id
where p.slug = 'ai_for_everyone' and u.order_num = 6
on conflict (unit_id, order_num) do nothing;
