-- PREVIEW SEED — review & approve before applying with the service key.
-- Program: ai_for_everyone  Unit 7 (Day 7)  Lesson 1
-- Generated by build_seed.py after passing validate_lesson.py.

insert into units (program_id, order_num, label, title, theme)
select id, 7, 'Day 7', 'Your AI Workflow: Putting It All Together', ''
from programs where slug = 'ai_for_everyone'
on conflict (program_id, order_num) do nothing;

insert into lessons (unit_id, order_num, title, est_minutes, steps)
select u.id, 1, 'Daily Life with AI', 15, $json$[
  {
    "id": "d7_s1",
    "type": "info",
    "title": "Welcome to Day 7 — Your Final Day",
    "body": "This is the last day of the first week. Today you will bring everything together into a daily AI workflow that works for your life.",
    "audioUrl": null,
    "primaryButton": "Let's finish strong",
    "xp": 3
  },
  {
    "id": "d7_s2",
    "type": "scenario_card",
    "title": "Your week in review",
    "body": "Day 1: Asking clear questions. Day 2: Writing specific prompts. Day 3: Drafting and revising. Day 4: Summarizing and planning. Day 5: Learning and researching. Day 6: Brainstorming. Now you put it all together.",
    "audioUrl": null,
    "primaryButton": "That is a lot of progress",
    "xp": 3
  },
  {
    "id": "d7_s3",
    "type": "info",
    "title": "Your AI workflow",
    "body": "A daily AI practice has three parts:\n\n1. Morning check — what does today need?\n2. Throughout the day — ask AI as you work\n3. Evening reflection — what did you learn?\n\nEven five minutes of AI use per day adds up.",
    "audioUrl": null,
    "primaryButton": "Show me the workflow",
    "xp": 3
  },
  {
    "id": "d7_s4",
    "type": "mc",
    "title": "Best morning use of AI",
    "question": "What is the most useful way to start your day with AI?",
    "options": [
      "Ask AI general questions about the news",
      "Paste your day's tasks and ask AI to organize them by priority and time",
      "Ask AI to tell you a joke"
    ],
    "correct": 1,
    "feedback": [
      "Not bad, but it does not shape your day.",
      "Yes. Organizing tasks first thing sets a productive direction.",
      "Fun, but not the most practical use."
    ],
    "xp": 10
  },
  {
    "id": "d7_s5",
    "type": "highlight",
    "title": "Find the AI opportunities",
    "body": "Today I need to: write a polite decline email, plan dinner for guests, understand a confusing bill, and decide between two weekend activities.",
    "highlights": [
      "write a polite decline email",
      "plan dinner for guests",
      "understand a confusing bill",
      "decide between two weekend activities"
    ],
    "xp": 6
  },
  {
    "id": "d7_s6",
    "type": "tf",
    "title": "True or false?",
    "question": "The key to building an AI habit is using it for small, everyday tasks — not just big projects.",
    "correct": true,
    "feedback": [
      "Correct. Daily small wins build the habit.",
      "Yes. Asking AI for small help multiple times a day builds the skill."
    ],
    "xp": 5
  },
  {
    "id": "d7_s7",
    "type": "info",
    "title": "Your six AI superpowers",
    "body": "1. Ask clear questions (Day 1)\n2. Write specific prompts with goal, detail, format (Day 2)\n3. Draft and revise writing (Day 3)\n4. Summarize, organize, plan (Day 4)\n5. Learn new topics with analogies (Day 5)\n6. Brainstorm and expand ideas (Day 6)",
    "audioUrl": null,
    "primaryButton": "I have these skills",
    "xp": 3
  },
  {
    "id": "d7_s8",
    "type": "good_fit",
    "title": "Good fit?",
    "question": "I have a doctor's appointment at 10am, need to pick up dry cleaning, and have a work call at 2pm. Create a timeline for my day.",
    "correct": "good",
    "feedback": [
      "Yes. This is exactly the kind of daily planning AI excels at.",
      "Right. Daily logistics with constraints are a perfect fit."
    ],
    "xp": 5
  },
  {
    "id": "d7_s9a",
    "type": "info",
    "title": "AI knows a lot, but not everything",
    "body": "AI is amazing with information, but feelings need a real person. Let us test your sense of boundaries.",
    "audioUrl": null,
    "primaryButton": "I agree",
    "xp": 3
  },
  {
    "id": "d7_s9",
    "type": "good_fit",
    "title": "Good fit?",
    "question": "Tell me exactly how my partner is feeling right now.",
    "correct": "notideal",
    "feedback": [
      "AI cannot read minds or emotions — ask your partner directly.",
      "Exactly. For personal feelings, talk to the person."
    ],
    "xp": 5
  },
  {
    "id": "d7_s10",
    "type": "info",
    "title": "AI is a tool, not a replacement",
    "body": "AI is great for writing, planning, organizing, learning, and brainstorming. It saves time and opens new possibilities. But your judgment, values, and personal touch are what make the results truly yours. You are still in charge.",
    "audioUrl": null,
    "primaryButton": "I understand",
    "xp": 3
  },
  {
    "id": "d7_s11",
    "type": "builder",
    "title": "Build your daily AI habit plan",
    "fields": [
      {
        "id": "habit",
        "label": "When will you use AI regularly?",
        "placeholder": "every morning with my coffee"
      },
      {
        "id": "first_task",
        "label": "What will you ask AI first?",
        "placeholder": "organize my tasks for the day"
      },
      {
        "id": "goal",
        "label": "What do you want to get better at?",
        "placeholder": "writing better prompts automatically"
      }
    ],
    "template": "My AI habit plan:\n- When: {{habit}}\n- First task: {{first_task}}\n- My goal: {{goal}}",
    "primaryButton": "Save my plan",
    "xp": 20
  },
  {
    "id": "d7_s12",
    "type": "info",
    "title": "This is just the beginning",
    "body": "The 7-day program is just the start. AI evolves fast, and the skill is staying curious. Whenever you face a new challenge, ask yourself: 'Could AI help with this?' More often than not, the answer is yes.",
    "audioUrl": null,
    "primaryButton": "I am ready",
    "xp": 3
  },
  {
    "id": "d7_s13",
    "type": "fillblank",
    "title": "Fill in the blank",
    "question": "AI is a powerful ______, but your judgment and values are what make the results truly yours.",
    "answer": "tool",
    "aliases": [
      "assistant",
      "helper",
      "resource"
    ],
    "feedback": [
      "Exactly. A tool that amplifies what you already bring.",
      "Close. The answer is 'tool' — you are in charge, AI assists."
    ],
    "xp": 5
  },
  {
    "id": "d7_s14",
    "type": "match",
    "title": "Match the skill to the day",
    "pairs": [
      {
        "left": "Goal, detail, format",
        "right": "Day 2 — Write specific prompts"
      },
      {
        "left": "Ask for revision",
        "right": "Day 3 — Draft and revise"
      },
      {
        "left": "Use analogies to learn",
        "right": "Day 5 — Research and learn"
      }
    ],
    "xp": 12
  },
  {
    "id": "d7_s15",
    "type": "reflection",
    "title": "Your week in review",
    "questions": [
      {
        "id": "biggest_change",
        "type": "single_choice",
        "label": "What is the biggest way AI will help you after this week?",
        "options": [
          "Writing and communicating better",
          "Organizing and planning my day",
          "Learning new things faster",
          "Getting creative ideas"
        ]
      },
      {
        "id": "next_step",
        "type": "textarea",
        "label": "What is one thing you will do differently starting tomorrow?"
      }
    ],
    "xp": 15
  },
  {
    "id": "d7_s16",
    "type": "compare",
    "title": "Compare your first prompt to your latest",
    "question": "Think back to your first prompt on Day 1. Compare it with what you just wrote. How has your skill improved? Write your observation.",
    "primaryButton": "I see my progress",
    "xp": 10
  },
  {
    "id": "d7_s17",
    "type": "quiz",
    "title": "Week 1 mastery check",
    "questions": [
      {
        "id": "q1",
        "type": "mc",
        "question": "What are the three parts of a clear prompt?",
        "options": [
          "Greeting, body, closing",
          "Goal, details, format",
          "Short, fast, simple"
        ],
        "correct": 1
      },
      {
        "id": "q2",
        "type": "mc",
        "question": "If AI's first draft is wrong, what should you do?",
        "options": [
          "Give up on that topic",
          "Ask AI to revise with specific changes",
          "Use a different device"
        ],
        "correct": 1
      },
      {
        "id": "q3",
        "type": "tf",
        "question": "You should use AI for medical diagnoses without checking with a doctor.",
        "correct": false
      },
      {
        "id": "q4",
        "type": "mc",
        "question": "AI is best at brainstorming when you:",
        "options": [
          "Keep your request very short",
          "Describe your constraints and ask for many options",
          "Use only one AI tool"
        ],
        "correct": 1
      },
      {
        "id": "q5",
        "type": "mc",
        "question": "The key to building an AI habit is:",
        "options": [
          "Using it only for big, important projects",
          "Using it for small, everyday tasks consistently",
          "Reading about AI every day"
        ],
        "correct": 1
      }
    ],
    "xp": 25
  },
  {
    "id": "d7_s18",
    "type": "badge_unlock",
    "badgeSlug": "week1_graduate"
  },
  {
    "id": "d7_s19",
    "type": "streak_commitment",
    "commitOptions": [
      7,
      14,
      28,
      60
    ]
  },
  {
    "id": "d7_s20",
    "type": "completion",
    "title": "Week 1 complete!",
    "body": "Congratulations — you completed the first 7 days of AI for Everyone. You now have six practical AI skills you can use every day. Keep asking, keep learning, and remember: you are in charge.",
    "primaryButton": "See my journey"
  }
]$json$::jsonb
from units u join programs p on p.id = u.program_id
where p.slug = 'ai_for_everyone' and u.order_num = 7
on conflict (unit_id, order_num) do nothing;
